"""create sla-template table

Revision ID: 089b4b67cf06
Revises: 8ca8bf847f42
Create Date: 2026-02-28 15:31:19.265726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b4b67cf06'
down_revision: Union[str, Sequence[str], None] = '8ca8bf847f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('telecaller_action_time', sa.Integer(), nullable=False),
    sa.Column('coordinator_verification_time', sa.Integer(), nullable=False),
    sa.Column('submission_time_limit', sa.Integer(), nullable=False),
    sa.Column('escalation_after', sa.Integer(), nullable=False),
    sa.Column('auto_revert_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='slastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_templates_id'), 'sla_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_templates_id'), table_name='sla_templates')
    op.drop_table('sla_templates')
    # ### end Alembic commands ###
