"""add experience  column to telecaller_profiles

Revision ID: 1164c0065386
Revises: fd4b34013e34
Create Date: 2026-03-06 12:29:14.300274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1164c0065386'
down_revision: Union[str, Sequence[str], None] = 'fd4b34013e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telecaller_profiles', sa.Column('experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telecaller_profiles', 'experience')
    # ### end Alembic commands ###
