"""add bank__id and product_id  to cases

Revision ID: 1a3ee77d0c80
Revises: d11fdc945f12
Create Date: 2026-03-12 13:19:43.963350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3ee77d0c80'
down_revision: Union[str, Sequence[str], None] = 'd11fdc945f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cases', 'banks', ['bank_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'bank_id')
    op.drop_column('cases', 'product_id')
    # ### end Alembic commands ###
