"""create documents and cases

Revision ID: 247abdd4601f
Revises: 83d7fd9ea11c
Create Date: 2026-03-10 14:01:27.570544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247abdd4601f'
down_revision: Union[str, Sequence[str], None] = '83d7fd9ea11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('emirates_id', sa.String(length=50), nullable=True),
    sa.Column('passport_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['product_type'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('emirates_id_front_url', sa.String(length=255), nullable=True),
    sa.Column('emirates_id_back_url', sa.String(length=255), nullable=True),
    sa.Column('passport_copy_url', sa.String(length=255), nullable=True),
    sa.Column('residencevisa_url', sa.String(length=255), nullable=True),
    sa.Column('salary_certificate_url', sa.String(length=255), nullable=True),
    sa.Column('bank_statement_last_3_months_url', sa.String(length=255), nullable=True),
    sa.Column('bank_statement_last_6_months_url', sa.String(length=255), nullable=True),
    sa.Column('trade_license_url', sa.String(length=255), nullable=True),
    sa.Column('liability_letter_url', sa.String(length=255), nullable=True),
    sa.Column('noc_from_employer_url', sa.String(length=255), nullable=True),
    sa.Column('security_cheque_url', sa.String(length=255), nullable=True),
    sa.Column('utility_bill_url', sa.String(length=255), nullable=True),
    sa.Column('tenancy_contract_url', sa.String(length=255), nullable=True),
    sa.Column('proof_of_address_url', sa.String(length=255), nullable=True),
    sa.Column('last_3_month_payslips_url', sa.String(length=255), nullable=True),
    sa.Column('last_6_month_payslips_url', sa.String(length=255), nullable=True),
    sa.Column('company_id_card_url', sa.String(length=255), nullable=True),
    sa.Column('labor_contract_url', sa.String(length=255), nullable=True),
    sa.Column('employment_letter_url', sa.String(length=255), nullable=True),
    sa.Column('bank_account_statement_url', sa.String(length=255), nullable=True),
    sa.Column('credit_report_url', sa.String(length=255), nullable=True),
    sa.Column('existing_loan_statement_url', sa.String(length=255), nullable=True),
    sa.Column('property_document_url', sa.String(length=255), nullable=True),
    sa.Column('vehicle_registration_url', sa.String(length=255), nullable=True),
    sa.Column('business_plan_url', sa.String(length=255), nullable=True),
    sa.Column('financial_statement_url', sa.String(length=255), nullable=True),
    sa.Column('tax_return_url', sa.String(length=255), nullable=True),
    sa.Column('memorandum_of_association_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_documents')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
