"""added relation case and lead

Revision ID: 611cd19b37c1
Revises: 91c2508edd85
Create Date: 2026-03-11 11:58:19.648667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611cd19b37c1'
down_revision: Union[str, Sequence[str], None] = '91c2508edd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'lead_id')
    # ### end Alembic commands ###
