"""add description column to loan_types

Revision ID: 63495631777c
Revises: 74c7faf691a9
Create Date: 2026-02-26 11:42:34.272655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63495631777c'
down_revision: Union[str, Sequence[str], None] = '74c7faf691a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_types', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_types', 'description')
    # ### end Alembic commands ###
