"""add name  column to admin profile and remov name colum user table

Revision ID: 6c0912481ad6
Revises: 1b1a5a600211
Create Date: 2026-02-25 11:27:13.783716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0912481ad6'
down_revision: Union[str, Sequence[str], None] = '1b1a5a600211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_profiles', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('admin_profiles', 'name')
    # ### end Alembic commands ###
