"""updated time zones

Revision ID: 6df087fd3c34
Revises: d25afefbb987
Create Date: 2026-03-10 14:26:18.203648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df087fd3c34'
down_revision: Union[str, Sequence[str], None] = 'd25afefbb987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'product_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('cases_lead_id_fkey'), 'cases', type_='foreignkey')
    op.drop_column('cases', 'lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cases_lead_id_fkey'), 'cases', 'leads', ['lead_id'], ['id'])
    op.alter_column('cases', 'product_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
