"""make telecaller fields nullable

Revision ID: 79a47d6bb94e
Revises: 1164c0065386
Create Date: 2026-03-06 12:37:52.653977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a47d6bb94e'
down_revision: Union[str, Sequence[str], None] = '1164c0065386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telecaller_profiles', 'target_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('telecaller_profiles', 'shift_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('telecaller_profiles', 'reporting_manager',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telecaller_profiles', 'reporting_manager',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('telecaller_profiles', 'shift_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('telecaller_profiles', 'target_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
