"""create commission table

Revision ID: 7e1d58cba4bf
Revises: 20ff86be98ff
Create Date: 2026-03-05 10:34:14.549027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1d58cba4bf'
down_revision: Union[str, Sequence[str], None] = '20ff86be98ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commission_type', sa.Enum('percentage', 'flat', name='commissiontypeenum'), nullable=False),
    sa.Column('commission_value', sa.Float(), nullable=False),
    sa.Column('agent_share', sa.Float(), nullable=False),
    sa.Column('telecaller_share', sa.Float(), nullable=False),
    sa.Column('coordinator_share', sa.Float(), nullable=False),
    sa.Column('effective_from_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='commissionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_id'), 'commissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissions_id'), table_name='commissions')
    op.drop_table('commissions')
    # ### end Alembic commands ###
