"""create email configuration table

Revision ID: 83d7fd9ea11c
Revises: 27d3dc111c0e
Create Date: 2026-03-10 10:49:53.525406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d7fd9ea11c'
down_revision: Union[str, Sequence[str], None] = '27d3dc111c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(), nullable=False),
    sa.Column('smtp_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_configurations_id'), 'email_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_configurations_id'), table_name='email_configurations')
    op.drop_table('email_configurations')
    # ### end Alembic commands ###
