"""update loan type table

Revision ID: 9ea8fb7403ef
Revises: b9beac476796
Create Date: 2026-02-28 14:06:06.141160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea8fb7403ef'
down_revision: Union[str, Sequence[str], None] = 'b9beac476796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_types', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('loan_types', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_types', 'updated_at')
    op.drop_column('loan_types', 'created_at')
    # ### end Alembic commands ###
