"""added indexing commission models

Revision ID: a482ad21bf49
Revises: c7238ae7ef94
Create Date: 2026-03-05 11:27:30.575138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a482ad21bf49'
down_revision: Union[str, Sequence[str], None] = 'c7238ae7ef94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_commission_bank', 'commissions', ['bank_id'], unique=False)
    op.create_index('idx_commission_bank_product', 'commissions', ['bank_id', 'product_id'], unique=False)
    op.create_index('idx_commission_effective_date', 'commissions', ['effective_from_date'], unique=False)
    op.create_index('idx_commission_product', 'commissions', ['product_id'], unique=False)
    op.create_index('idx_commission_status', 'commissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_commission_status', table_name='commissions')
    op.drop_index('idx_commission_product', table_name='commissions')
    op.drop_index('idx_commission_effective_date', table_name='commissions')
    op.drop_index('idx_commission_bank_product', table_name='commissions')
    op.drop_index('idx_commission_bank', table_name='commissions')
    # ### end Alembic commands ###
