"""added column name table coordinator

Revision ID: b43a401a537c
Revises: 4800f54233b6
Create Date: 2026-03-05 14:12:41.602084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43a401a537c'
down_revision: Union[str, Sequence[str], None] = '4800f54233b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telecaller_profiles', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telecaller_profiles', 'name')
    # ### end Alembic commands ###
