"""create product table

Revision ID: be57998a16fe
Revises: 856134cf7d61
Create Date: 2026-03-02 16:15:55.076938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be57998a16fe'
down_revision: Union[str, Sequence[str], None] = '856134cf7d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('customer_segment', sa.Enum('salaried', 'selfemployed', 'sme', name='customer_segment_enum'), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('loan_type_id', sa.Integer(), nullable=False),
    sa.Column('sla_template_id', sa.Integer(), nullable=True),
    sa.Column('min_loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_tenure', sa.Integer(), nullable=False),
    sa.Column('max_tenure', sa.Integer(), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='product_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ),
    sa.ForeignKeyConstraint(['sla_template_id'], ['sla_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
