"""create refresh table

Revision ID: d073e39aed79
Revises: 61834b4f9cf8
Create Date: 2026-02-23 13:04:12.719954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd073e39aed79'
down_revision: Union[str, Sequence[str], None] = '61834b4f9cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_profiles', sa.Column('emirates_id', sa.String(length=100), nullable=True))
    op.add_column('agent_profiles', sa.Column('nationality', sa.String(length=100), nullable=False))
    op.add_column('agent_profiles', sa.Column('business_name', sa.String(length=100), nullable=True))
    op.add_column('agent_profiles', sa.Column('year_of_experience', sa.Integer(), nullable=True))
    op.add_column('agent_profiles', sa.Column('account_holder_name', sa.String(length=255), nullable=True))
    op.add_column('agent_profiles', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('agent_profiles', sa.Column('iban', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'agent_profiles', ['emirates_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_profiles', type_='unique')
    op.drop_column('agent_profiles', 'iban')
    op.drop_column('agent_profiles', 'bank_name')
    op.drop_column('agent_profiles', 'account_holder_name')
    op.drop_column('agent_profiles', 'year_of_experience')
    op.drop_column('agent_profiles', 'business_name')
    op.drop_column('agent_profiles', 'nationality')
    op.drop_column('agent_profiles', 'emirates_id')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
