"""add telecaller_id to cases

Revision ID: d11fdc945f12
Revises: 611cd19b37c1
Create Date: 2026-03-12 12:29:45.085043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11fdc945f12'
down_revision: Union[str, Sequence[str], None] = '611cd19b37c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('telecaller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['telecaller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'telecaller_id')
    # ### end Alembic commands ###
