"""create table bank and  loan type

Revision ID: dd25043d8db9
Revises: 6c0912481ad6
Create Date: 2026-02-25 23:42:58.884416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd25043d8db9'
down_revision: Union[str, Sequence[str], None] = '6c0912481ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=255), nullable=False),
    sa.Column('default_tat_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('loan_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_loan_types',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('loan_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_id', 'loan_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_loan_types')
    op.drop_table('loan_types')
    op.drop_table('banks')
    # ### end Alembic commands ###
