"""updated table coordinator

Revision ID: e991595220f2
Revises: a482ad21bf49
Create Date: 2026-03-05 13:20:20.811964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e991595220f2'
down_revision: Union[str, Sequence[str], None] = 'a482ad21bf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinator_profiles', sa.Column('emirates_id', sa.String(length=100), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('nationality', sa.String(length=100), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('experience', sa.String(length=100), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('account_holder_name', sa.String(), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('account_number', sa.String(), nullable=False))
    op.add_column('coordinator_profiles', sa.Column('iban', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'coordinator_profiles', ['emirates_id'])
    op.drop_column('coordinator_profiles', 'region')
    op.drop_column('coordinator_profiles', 'team_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinator_profiles', sa.Column('team_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('coordinator_profiles', sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coordinator_profiles', type_='unique')
    op.drop_column('coordinator_profiles', 'iban')
    op.drop_column('coordinator_profiles', 'account_number')
    op.drop_column('coordinator_profiles', 'bank_name')
    op.drop_column('coordinator_profiles', 'account_holder_name')
    op.drop_column('coordinator_profiles', 'experience')
    op.drop_column('coordinator_profiles', 'nationality')
    op.drop_column('coordinator_profiles', 'emirates_id')
    # ### end Alembic commands ###
