"""add column to telecaller_profiles

Revision ID: fd4b34013e34
Revises: dd177a60107e
Create Date: 2026-03-06 12:27:52.917160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4b34013e34'
down_revision: Union[str, Sequence[str], None] = 'dd177a60107e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telecaller_profiles', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('emirates_id', sa.String(length=100), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('nationality', sa.String(length=100), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('account_holder_name', sa.String(), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('account_number', sa.String(), nullable=False))
    op.add_column('telecaller_profiles', sa.Column('iban', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'telecaller_profiles', ['emirates_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telecaller_profiles', type_='unique')
    op.drop_column('telecaller_profiles', 'iban')
    op.drop_column('telecaller_profiles', 'account_number')
    op.drop_column('telecaller_profiles', 'bank_name')
    op.drop_column('telecaller_profiles', 'account_holder_name')
    op.drop_column('telecaller_profiles', 'nationality')
    op.drop_column('telecaller_profiles', 'emirates_id')
    op.drop_column('telecaller_profiles', 'phone')
    # ### end Alembic commands ###
